title: Piyush The Developer
author: Piyush Mourya
email: mauryapiyush76@gmail.com
description: This is a github page i am using for my blog

# social links
twitter_username: peeingyush
github_username: mauryapiyush76

show_excerpts: true # set to false to remove excerpts on the homepage

# Build settings
theme: minima 
