title: Piyush The Dev
author: Piyush Mourya
email: mauryapiyush76@gmail.com
description: Piyush the developer is wild
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
